### ISSUE TITLE
Reunião 10-03-2016

### ISSUE THREAD

**Issue by laizaribeiro** [ControlK/controlk-doc#3]
Pessoal,

Pensei em reunirmos amanhã para conversar sobre o vídeo e o elevator pitch que terá que ser entregue na próxima semana.
O que acham?
Minha sugestão é as 9h, no lab 2.05.

Até mais!

**Comment by pedroSilvaUFSJ** [comment]
confirmado!

**Comment by xfilipe** [comment]
confirmado!

**Comment by AnaRoberta** [comment]
Ok! :)

**Comment by acr929** [comment]
ok.

**Comment by ndogithub** [comment]
ok.

**Comment by laizaribeiro** [comment]
Feedback da reunião de hoje (10-03-2016):

Foi realizada a definição das tarefas para as entregas do dia 16/março e 23/março. Para as pessoas que não compareceram e não concordam com a divisão, é só falar que fazemos a mudança sem problemas:

Laíza e Ana Roberta: Montar o vídeo **(entrega dia 23/março)**.
Filipe e Allyson: montar texto + ambiente (apresentação) **(entrega dia 23/março)**.
Fernando e Pedro: Montar elevator pitch (Pedro irá apresentar) **(entrega dia 16/março)**

Até mais!

**Comment by ndogithub** [comment]
Por mim tudo bem. Pedro, como estão seus horários pra gente começar a discutir essa tarefa ? :)

**Comment by AnaRoberta** [comment]
Quarta-feira, após às 15:05 --> montagem do vídeo!

**Comment by laizaribeiro** [comment]
Filipe e Ally,

Retifiquei o post sobre a entrega, conforme falei no grupo do face. 
Só para confirmar:

Filipe e Allyson: montar texto + ambiente (apresentação) **(entrega dia 16/março).**

Até mais!

**Comment by ndogithub** [comment]
Eu e Pedro combinamos que vamos fazer o Elevator pitch no Sabado dia 12/03/16 a tarde.

**Comment by acr929** [comment]
E ae Filipe. Bora combinar? Esse fim de semana dá pra mim
... Te adicionei,no face.
Em 11/03/2016 10:51, "Fernando Carvalho" <notifications@github.com>
escreveu:
