### ISSUE TITLE
Próxima reunião: 17-06-2016

### ISSUE THREAD

**Issue by laizaribeiro** [ControlK/controlk-doc#4]
Pessoal,

Na reunião de hoje (10-06) foi sugerido para que nos reuníssemos na próxima quinta (17/06) para definir as funções para começar o desenvolvimento do projeto. Além disso, podemos definir também a entrega da primeira parte do projeto desenvolvido para não nos enrolarmos no final do período.

O que acham?

Até!

**Comment by AnaRoberta** [comment]
Quinta-feira, 16/03, eu tenho dentista marcado... agora que tô vendo aqui! :/

**Comment by AnaRoberta** [comment]
Quinta-feira, 17/03, eu tenho dentista marcado... agora que tô vendo aqui! :/

**Comment by ndogithub** [comment]
Pessoal, eu acho que podemos marcar essas reuniões antes da aula ou após as aulas, pq todos já estão lá, ou definir um horario online que todos possam participar, porque, no meu caso por exemplo, tenho que me deslocar ate o ctan quinta de manha só pra reuniao e depois a aula e so 15 da tarde, quebra.
