### ISSUE TITLE
Texto e Ambiente (Apresentação) - 16/03

### ISSUE THREAD

**Issue by xfilipe** [ControlK/controlk-doc#6]
Galera tamo quase terminando a apresentação,  ta bem simples, só sumarizando como ta o controlK atual falando das features e problemas, o que foi proposto de melhoria e nosso plano em alto nivel para resolver os problemas. No fim fala dos integrantes e os ambientes que estamos usando... comentem ai o que tem que mudar ou mudem vcs mesmos pelo link https://docs.google.com/presentation/d/1HlzXpJ1w1f2WZiMGW862cOnoY7kqCXEcbtJ8Dz90zVk/edit?usp=sharing

**Comment by AnaRoberta** [comment]
Tá ótimo! :D

**Comment by AnaRoberta** [comment]
Mudei lá o nome dos integrantes!
...mas estou na dúvida se deixa todos como desenvolvedores ou não...

**Comment by xfilipe** [comment]
Fiz algumas alterações para finalizar, quem quiser dar uma olhada https://docs.google.com/presentation/d/1HlzXpJ1w1f2WZiMGW862cOnoY7kqCXEcbtJ8Dz90zVk/edit?usp=sharing

**Comment by ndogithub** [comment]
Ta bacana. :)
